// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dataservice/dataservice.proto

package dataservice

import (
	fmt "fmt"
	_ "github.com/dexinq/utils/proto/controller"
	_ "github.com/dexinq/utils/proto/global"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataAcquire struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64    `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	DataTable            string   `protobuf:"bytes,4,opt,name=DataTable,proto3" json:"DataTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAcquire) Reset()         { *m = DataAcquire{} }
func (m *DataAcquire) String() string { return proto.CompactTextString(m) }
func (*DataAcquire) ProtoMessage()    {}
func (*DataAcquire) Descriptor() ([]byte, []int) {
	return fileDescriptor_9162601e6363fd08, []int{0}
}

func (m *DataAcquire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAcquire.Unmarshal(m, b)
}
func (m *DataAcquire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAcquire.Marshal(b, m, deterministic)
}
func (m *DataAcquire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAcquire.Merge(m, src)
}
func (m *DataAcquire) XXX_Size() int {
	return xxx_messageInfo_DataAcquire.Size(m)
}
func (m *DataAcquire) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAcquire.DiscardUnknown(m)
}

var xxx_messageInfo_DataAcquire proto.InternalMessageInfo

func (m *DataAcquire) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *DataAcquire) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *DataAcquire) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *DataAcquire) GetDataTable() string {
	if m != nil {
		return m.DataTable
	}
	return ""
}

type DataObject struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Data                 int64    `protobuf:"varint,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataObject) Reset()         { *m = DataObject{} }
func (m *DataObject) String() string { return proto.CompactTextString(m) }
func (*DataObject) ProtoMessage()    {}
func (*DataObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_9162601e6363fd08, []int{1}
}

func (m *DataObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataObject.Unmarshal(m, b)
}
func (m *DataObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataObject.Marshal(b, m, deterministic)
}
func (m *DataObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataObject.Merge(m, src)
}
func (m *DataObject) XXX_Size() int {
	return xxx_messageInfo_DataObject.Size(m)
}
func (m *DataObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DataObject.DiscardUnknown(m)
}

var xxx_messageInfo_DataObject proto.InternalMessageInfo

func (m *DataObject) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *DataObject) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type DataDescription struct {
	Do                   []*DataObject `protobuf:"bytes,1,rep,name=do,proto3" json:"do,omitempty"`
	DataSourceName       string        `protobuf:"bytes,2,opt,name=DataSourceName,proto3" json:"DataSourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DataDescription) Reset()         { *m = DataDescription{} }
func (m *DataDescription) String() string { return proto.CompactTextString(m) }
func (*DataDescription) ProtoMessage()    {}
func (*DataDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_9162601e6363fd08, []int{2}
}

func (m *DataDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDescription.Unmarshal(m, b)
}
func (m *DataDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDescription.Marshal(b, m, deterministic)
}
func (m *DataDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDescription.Merge(m, src)
}
func (m *DataDescription) XXX_Size() int {
	return xxx_messageInfo_DataDescription.Size(m)
}
func (m *DataDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDescription.DiscardUnknown(m)
}

var xxx_messageInfo_DataDescription proto.InternalMessageInfo

func (m *DataDescription) GetDo() []*DataObject {
	if m != nil {
		return m.Do
	}
	return nil
}

func (m *DataDescription) GetDataSourceName() string {
	if m != nil {
		return m.DataSourceName
	}
	return ""
}

type Response struct {
	Status               int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Do                   []*DataObject `protobuf:"bytes,3,rep,name=do,proto3" json:"do,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9162601e6363fd08, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetDo() []*DataObject {
	if m != nil {
		return m.Do
	}
	return nil
}

func init() {
	proto.RegisterType((*DataAcquire)(nil), "dataservice.DataAcquire")
	proto.RegisterType((*DataObject)(nil), "dataservice.DataObject")
	proto.RegisterType((*DataDescription)(nil), "dataservice.DataDescription")
	proto.RegisterType((*Response)(nil), "dataservice.Response")
}

func init() {
	proto.RegisterFile("proto/dataservice/dataservice.proto", fileDescriptor_9162601e6363fd08)
}

var fileDescriptor_9162601e6363fd08 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x51, 0x8b, 0xd4, 0x30,
	0x10, 0xb6, 0xdb, 0xf3, 0x74, 0xb3, 0xac, 0xae, 0x03, 0x6a, 0x2d, 0x87, 0x2c, 0x15, 0x74, 0x9f,
	0xba, 0xb8, 0x3e, 0x09, 0x72, 0xb0, 0x78, 0x87, 0x08, 0xe2, 0x41, 0xf7, 0x7c, 0xf4, 0x21, 0x6d,
	0x87, 0x35, 0x47, 0xdb, 0xf4, 0x92, 0xa9, 0xe8, 0xb3, 0xcf, 0xfe, 0x3b, 0x7f, 0x90, 0x24, 0x4d,
	0x6d, 0xf4, 0x0e, 0x05, 0x9f, 0x32, 0xf3, 0xcd, 0x7c, 0x5f, 0xbe, 0x4c, 0x86, 0x3d, 0x69, 0x95,
	0x24, 0xb9, 0x2e, 0x39, 0x71, 0x8d, 0xea, 0xb3, 0x28, 0xd0, 0x8f, 0x53, 0x5b, 0x85, 0x99, 0x07,
	0xc5, 0xcf, 0xf7, 0x82, 0x3e, 0x75, 0x79, 0x5a, 0xc8, 0x7a, 0x5d, 0xe2, 0x17, 0xd1, 0x5c, 0xae,
	0x3b, 0x12, 0x95, 0x5e, 0xf7, 0x4a, 0xfb, 0x4a, 0xe6, 0xbc, 0x72, 0x47, 0xcf, 0x8f, 0x5f, 0xfe,
	0x9d, 0x52, 0xc8, 0x86, 0x94, 0xac, 0x2a, 0x54, 0x5e, 0xd8, 0x53, 0x93, 0x6f, 0x01, 0x9b, 0x9d,
	0x70, 0xe2, 0xdb, 0xe2, 0xb2, 0x13, 0x0a, 0xe1, 0x31, 0x63, 0x26, 0xdd, 0xc9, 0x4e, 0x15, 0x18,
	0x05, 0xcb, 0x60, 0x35, 0xcd, 0x3c, 0x04, 0x8e, 0xd8, 0x74, 0x47, 0x5c, 0xd1, 0xb9, 0xa8, 0x31,
	0x9a, 0x2c, 0x83, 0x55, 0x98, 0x8d, 0x00, 0x44, 0xec, 0xd6, 0x69, 0x53, 0xda, 0x5a, 0x68, 0x6b,
	0x43, 0x6a, 0x78, 0x46, 0xe5, 0x9c, 0xe7, 0x15, 0x46, 0x07, 0x56, 0x76, 0x04, 0x92, 0xe3, 0xfe,
	0xd6, 0xb3, 0xfc, 0x02, 0x0b, 0x32, 0xbd, 0x86, 0xb3, 0x23, 0x5e, 0xb7, 0xd6, 0x42, 0x98, 0x8d,
	0x00, 0x00, 0x3b, 0x30, 0xbd, 0xee, 0x72, 0x1b, 0x27, 0x39, 0xbb, 0x6b, 0xce, 0x13, 0xd4, 0x85,
	0x12, 0x2d, 0x09, 0xd9, 0xc0, 0x33, 0x36, 0x29, 0x65, 0x14, 0x2c, 0xc3, 0xd5, 0x6c, 0xf3, 0x30,
	0xf5, 0x67, 0x3e, 0xde, 0x94, 0x4d, 0x4a, 0x09, 0x4f, 0xd9, 0x9d, 0xf1, 0x7d, 0xef, 0xb9, 0x7b,
	0xd6, 0x34, 0xfb, 0x03, 0x4d, 0x3e, 0xb2, 0xdb, 0x19, 0xea, 0x56, 0x36, 0x1a, 0xe1, 0x01, 0x3b,
	0xd4, 0xc4, 0xa9, 0xd3, 0xd6, 0xde, 0xcd, 0xcc, 0x65, 0xb0, 0x60, 0x61, 0xad, 0xf7, 0x4e, 0xc0,
	0x84, 0xce, 0x46, 0xf8, 0x4f, 0x1b, 0x9b, 0xef, 0xee, 0x23, 0x76, 0x7d, 0x19, 0x8e, 0xfb, 0x81,
	0x99, 0x14, 0x21, 0xba, 0xc2, 0x74, 0xff, 0x15, 0xdf, 0xff, 0xad, 0x32, 0x18, 0x4c, 0x6e, 0x80,
	0x1b, 0xe9, 0xdb, 0x46, 0xa3, 0x22, 0x38, 0xba, 0x22, 0xe0, 0xcd, 0x2a, 0x5e, 0xa4, 0x6e, 0x9d,
	0x46, 0xfe, 0xe6, 0x47, 0xc0, 0xee, 0xbd, 0xfe, 0xb5, 0x2d, 0x83, 0xab, 0x57, 0x6c, 0xfe, 0x06,
	0x69, 0xc4, 0x61, 0x3e, 0x50, 0x4f, 0xeb, 0x96, 0xbe, 0xc6, 0x71, 0xea, 0x6d, 0xd8, 0xd8, 0xf6,
	0x4e, 0x68, 0xb2, 0x9e, 0xe6, 0xdb, 0xb2, 0xf4, 0xd8, 0x8f, 0xae, 0x6f, 0x3f, 0xcb, 0x2f, 0xae,
	0xf3, 0x04, 0x5b, 0xb6, 0xf8, 0xd0, 0x96, 0x9c, 0xf0, 0xbf, 0x25, 0xf2, 0x43, 0xbb, 0xf6, 0x2f,
	0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xf5, 0x0f, 0x39, 0x98, 0x03, 0x00, 0x00,
}
