// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/app/app.proto

package app

import (
	fmt "fmt"
	_ "github.com/dexinq/utils/proto/global"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppFilter struct {
	AppName              string   `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	AppType              string   `protobuf:"bytes,2,opt,name=AppType,proto3" json:"AppType,omitempty"`
	AppRegisterTime      int64    `protobuf:"varint,3,opt,name=AppRegisterTime,proto3" json:"AppRegisterTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppFilter) Reset()         { *m = AppFilter{} }
func (m *AppFilter) String() string { return proto.CompactTextString(m) }
func (*AppFilter) ProtoMessage()    {}
func (*AppFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac44f112c52ede2f, []int{0}
}

func (m *AppFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppFilter.Unmarshal(m, b)
}
func (m *AppFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppFilter.Marshal(b, m, deterministic)
}
func (m *AppFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppFilter.Merge(m, src)
}
func (m *AppFilter) XXX_Size() int {
	return xxx_messageInfo_AppFilter.Size(m)
}
func (m *AppFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AppFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AppFilter proto.InternalMessageInfo

func (m *AppFilter) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppFilter) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *AppFilter) GetAppRegisterTime() int64 {
	if m != nil {
		return m.AppRegisterTime
	}
	return 0
}

type AppObject struct {
	AppStatus            int32    `protobuf:"varint,1,opt,name=AppStatus,proto3" json:"AppStatus,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	AppType              string   `protobuf:"bytes,3,opt,name=AppType,proto3" json:"AppType,omitempty"`
	AppActionTime        int64    `protobuf:"varint,4,opt,name=AppActionTime,proto3" json:"AppActionTime,omitempty"`
	AppHidden            int32    `protobuf:"varint,5,opt,name=AppHidden,proto3" json:"AppHidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppObject) Reset()         { *m = AppObject{} }
func (m *AppObject) String() string { return proto.CompactTextString(m) }
func (*AppObject) ProtoMessage()    {}
func (*AppObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac44f112c52ede2f, []int{1}
}

func (m *AppObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppObject.Unmarshal(m, b)
}
func (m *AppObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppObject.Marshal(b, m, deterministic)
}
func (m *AppObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppObject.Merge(m, src)
}
func (m *AppObject) XXX_Size() int {
	return xxx_messageInfo_AppObject.Size(m)
}
func (m *AppObject) XXX_DiscardUnknown() {
	xxx_messageInfo_AppObject.DiscardUnknown(m)
}

var xxx_messageInfo_AppObject proto.InternalMessageInfo

func (m *AppObject) GetAppStatus() int32 {
	if m != nil {
		return m.AppStatus
	}
	return 0
}

func (m *AppObject) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppObject) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *AppObject) GetAppActionTime() int64 {
	if m != nil {
		return m.AppActionTime
	}
	return 0
}

func (m *AppObject) GetAppHidden() int32 {
	if m != nil {
		return m.AppHidden
	}
	return 0
}

type AppList struct {
	ObjList              []*AppObject `protobuf:"bytes,1,rep,name=ObjList,proto3" json:"ObjList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AppList) Reset()         { *m = AppList{} }
func (m *AppList) String() string { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()    {}
func (*AppList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac44f112c52ede2f, []int{2}
}

func (m *AppList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppList.Unmarshal(m, b)
}
func (m *AppList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppList.Marshal(b, m, deterministic)
}
func (m *AppList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppList.Merge(m, src)
}
func (m *AppList) XXX_Size() int {
	return xxx_messageInfo_AppList.Size(m)
}
func (m *AppList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppList.DiscardUnknown(m)
}

var xxx_messageInfo_AppList proto.InternalMessageInfo

func (m *AppList) GetObjList() []*AppObject {
	if m != nil {
		return m.ObjList
	}
	return nil
}

type AppData struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
	TableName            string   `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Dimensions           []string `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppData) Reset()         { *m = AppData{} }
func (m *AppData) String() string { return proto.CompactTextString(m) }
func (*AppData) ProtoMessage()    {}
func (*AppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac44f112c52ede2f, []int{3}
}

func (m *AppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppData.Unmarshal(m, b)
}
func (m *AppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppData.Marshal(b, m, deterministic)
}
func (m *AppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppData.Merge(m, src)
}
func (m *AppData) XXX_Size() int {
	return xxx_messageInfo_AppData.Size(m)
}
func (m *AppData) XXX_DiscardUnknown() {
	xxx_messageInfo_AppData.DiscardUnknown(m)
}

var xxx_messageInfo_AppData proto.InternalMessageInfo

func (m *AppData) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *AppData) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *AppData) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *AppData) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*AppFilter)(nil), "app.AppFilter")
	proto.RegisterType((*AppObject)(nil), "app.AppObject")
	proto.RegisterType((*AppList)(nil), "app.AppList")
	proto.RegisterType((*AppData)(nil), "app.AppData")
}

func init() { proto.RegisterFile("proto/app/app.proto", fileDescriptor_ac44f112c52ede2f) }

var fileDescriptor_ac44f112c52ede2f = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0xfd, 0xf2, 0x4d, 0x7f, 0xe8, 0x58, 0xad, 0x8c, 0x20, 0x43, 0x11, 0x09, 0xc1, 0x45, 0x56,
	0x09, 0xb6, 0xf8, 0x00, 0x41, 0x51, 0x17, 0x62, 0x21, 0xad, 0x0f, 0x30, 0x49, 0x2e, 0x75, 0x4a,
	0x92, 0xb9, 0x66, 0x26, 0xa2, 0x2b, 0x9f, 0x45, 0x7c, 0x51, 0x99, 0x49, 0xd2, 0xb4, 0x45, 0x17,
	0xdf, 0x22, 0x4c, 0xce, 0xb9, 0x9c, 0x9c, 0x33, 0x27, 0x97, 0x3e, 0xc3, 0x46, 0x19, 0x15, 0x0b,
	0x44, 0xfb, 0x44, 0x0e, 0x31, 0x22, 0x10, 0xd7, 0xaf, 0x8f, 0xd2, 0x7c, 0x6d, 0xb3, 0x28, 0x57,
	0x55, 0x5c, 0xc0, 0x0f, 0x59, 0x7f, 0x8b, 0x5b, 0x23, 0x4b, 0x1d, 0x77, 0x8a, 0x63, 0xa9, 0x32,
	0x51, 0xf6, 0x47, 0xa7, 0x0b, 0x24, 0x5d, 0x24, 0x88, 0xef, 0x65, 0x69, 0xa0, 0x61, 0x9c, 0xce,
	0x13, 0xc4, 0xcf, 0xa2, 0x02, 0xee, 0xf9, 0x5e, 0xb8, 0x48, 0x07, 0xd8, 0x4f, 0x0e, 0x3f, 0x11,
	0xf8, 0xfd, 0x79, 0x62, 0x21, 0x0b, 0xe9, 0x2a, 0x41, 0x4c, 0xe1, 0x28, 0xb5, 0x81, 0xe6, 0x20,
	0x2b, 0xe0, 0xc4, 0xf7, 0x42, 0x92, 0xde, 0xd2, 0xc1, 0x6f, 0xcf, 0x79, 0xed, 0xb2, 0x13, 0xe4,
	0x86, 0xbd, 0x70, 0x60, 0x6f, 0x84, 0x69, 0xb5, 0x73, 0x9b, 0xa6, 0x23, 0x71, 0x99, 0xe4, 0xfe,
	0xbf, 0x49, 0xc8, 0x75, 0x92, 0x57, 0xf4, 0x71, 0x82, 0x98, 0xe4, 0x46, 0xaa, 0xda, 0xe5, 0x98,
	0xb8, 0x1c, 0xd7, 0x64, 0xef, 0xfb, 0x51, 0x16, 0x05, 0xd4, 0x7c, 0x7a, 0xf6, 0xed, 0x88, 0x60,
	0xeb, 0xbe, 0xfe, 0x49, 0x6a, 0xc3, 0x42, 0x3a, 0xdf, 0x65, 0x27, 0xfb, 0xca, 0x3d, 0x9f, 0x84,
	0x8f, 0x36, 0x4f, 0x22, 0x5b, 0xf7, 0xf9, 0x06, 0xe9, 0x30, 0x0e, 0x7e, 0x39, 0xd1, 0x3b, 0x61,
	0x04, 0x7b, 0x49, 0xa9, 0x3d, 0xf7, 0xaa, 0x6d, 0xf2, 0xa1, 0xc4, 0x0b, 0xc6, 0xba, 0x1f, 0x44,
	0x56, 0xc2, 0xc5, 0xcd, 0x46, 0xc2, 0xaa, 0x0b, 0x59, 0x41, 0xad, 0xa5, 0xaa, 0x35, 0x27, 0x3e,
	0xb1, 0xea, 0x91, 0x61, 0xcf, 0xe9, 0xec, 0xbb, 0x28, 0x5b, 0xd0, 0x7c, 0xe2, 0x66, 0x3d, 0xda,
	0xfc, 0xf1, 0x28, 0x49, 0x10, 0xd9, 0x1b, 0xba, 0x7a, 0xdb, 0x80, 0x30, 0x30, 0xd6, 0x7c, 0x13,
	0x7a, 0xfd, 0x34, 0xea, 0x7f, 0x7f, 0x0a, 0x1a, 0x55, 0xad, 0x21, 0xb8, 0xb3, 0xb2, 0x2f, 0x58,
	0x3c, 0x58, 0x16, 0xd1, 0xe5, 0x07, 0x30, 0xff, 0xd0, 0x74, 0xdb, 0xb4, 0x5e, 0x0e, 0xd8, 0x95,
	0x74, 0x97, 0xcd, 0xdc, 0xc6, 0x6d, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x05, 0x9e, 0x1e,
	0xc0, 0x02, 0x00, 0x00,
}
