// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/app/app.proto

package app

import (
	fmt "fmt"
	global "github.com/dexinq/utils/proto/global"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for App service

type AppService interface {
	CreateAppObject(ctx context.Context, in *AppObject, opts ...client.CallOption) (*global.Response, error)
	UpdateAppObject(ctx context.Context, in *AppObject, opts ...client.CallOption) (*global.Response, error)
	GetAppObject(ctx context.Context, in *AppFilter, opts ...client.CallOption) (*AppList, error)
}

type appService struct {
	c    client.Client
	name string
}

func NewAppService(name string, c client.Client) AppService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "app"
	}
	return &appService{
		c:    c,
		name: name,
	}
}

func (c *appService) CreateAppObject(ctx context.Context, in *AppObject, opts ...client.CallOption) (*global.Response, error) {
	req := c.c.NewRequest(c.name, "App.CreateAppObject", in)
	out := new(global.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appService) UpdateAppObject(ctx context.Context, in *AppObject, opts ...client.CallOption) (*global.Response, error) {
	req := c.c.NewRequest(c.name, "App.UpdateAppObject", in)
	out := new(global.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appService) GetAppObject(ctx context.Context, in *AppFilter, opts ...client.CallOption) (*AppList, error) {
	req := c.c.NewRequest(c.name, "App.GetAppObject", in)
	out := new(AppList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppHandler interface {
	CreateAppObject(context.Context, *AppObject, *global.Response) error
	UpdateAppObject(context.Context, *AppObject, *global.Response) error
	GetAppObject(context.Context, *AppFilter, *AppList) error
}

func RegisterAppHandler(s server.Server, hdlr AppHandler, opts ...server.HandlerOption) error {
	type app interface {
		CreateAppObject(ctx context.Context, in *AppObject, out *global.Response) error
		UpdateAppObject(ctx context.Context, in *AppObject, out *global.Response) error
		GetAppObject(ctx context.Context, in *AppFilter, out *AppList) error
	}
	type App struct {
		app
	}
	h := &appHandler{hdlr}
	return s.Handle(s.NewHandler(&App{h}, opts...))
}

type appHandler struct {
	AppHandler
}

func (h *appHandler) CreateAppObject(ctx context.Context, in *AppObject, out *global.Response) error {
	return h.AppHandler.CreateAppObject(ctx, in, out)
}

func (h *appHandler) UpdateAppObject(ctx context.Context, in *AppObject, out *global.Response) error {
	return h.AppHandler.UpdateAppObject(ctx, in, out)
}

func (h *appHandler) GetAppObject(ctx context.Context, in *AppFilter, out *AppList) error {
	return h.AppHandler.GetAppObject(ctx, in, out)
}
