// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/controller/controller.proto

package controller

import (
	fmt "fmt"
	_ "github.com/dexinq/utils/proto/global"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControllerObj struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               int32          `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Ovn                  *OvnController `protobuf:"bytes,3,opt,name=ovn,proto3" json:"ovn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ControllerObj) Reset()         { *m = ControllerObj{} }
func (m *ControllerObj) String() string { return proto.CompactTextString(m) }
func (*ControllerObj) ProtoMessage()    {}
func (*ControllerObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5631c4d876e0f94, []int{0}
}

func (m *ControllerObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerObj.Unmarshal(m, b)
}
func (m *ControllerObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerObj.Marshal(b, m, deterministic)
}
func (m *ControllerObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerObj.Merge(m, src)
}
func (m *ControllerObj) XXX_Size() int {
	return xxx_messageInfo_ControllerObj.Size(m)
}
func (m *ControllerObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerObj.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerObj proto.InternalMessageInfo

func (m *ControllerObj) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ControllerObj) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ControllerObj) GetOvn() *OvnController {
	if m != nil {
		return m.Ovn
	}
	return nil
}

type OvnController struct {
	Nbip                 string   `protobuf:"bytes,1,opt,name=Nbip,proto3" json:"Nbip,omitempty"`
	Sbip                 string   `protobuf:"bytes,2,opt,name=Sbip,proto3" json:"Sbip,omitempty"`
	Nbport               string   `protobuf:"bytes,3,opt,name=Nbport,proto3" json:"Nbport,omitempty"`
	Sbport               string   `protobuf:"bytes,4,opt,name=Sbport,proto3" json:"Sbport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OvnController) Reset()         { *m = OvnController{} }
func (m *OvnController) String() string { return proto.CompactTextString(m) }
func (*OvnController) ProtoMessage()    {}
func (*OvnController) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5631c4d876e0f94, []int{1}
}

func (m *OvnController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvnController.Unmarshal(m, b)
}
func (m *OvnController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvnController.Marshal(b, m, deterministic)
}
func (m *OvnController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvnController.Merge(m, src)
}
func (m *OvnController) XXX_Size() int {
	return xxx_messageInfo_OvnController.Size(m)
}
func (m *OvnController) XXX_DiscardUnknown() {
	xxx_messageInfo_OvnController.DiscardUnknown(m)
}

var xxx_messageInfo_OvnController proto.InternalMessageInfo

func (m *OvnController) GetNbip() string {
	if m != nil {
		return m.Nbip
	}
	return ""
}

func (m *OvnController) GetSbip() string {
	if m != nil {
		return m.Sbip
	}
	return ""
}

func (m *OvnController) GetNbport() string {
	if m != nil {
		return m.Nbport
	}
	return ""
}

func (m *OvnController) GetSbport() string {
	if m != nil {
		return m.Sbport
	}
	return ""
}

type ControllerList struct {
	Co                   []*ControllerObj `protobuf:"bytes,1,rep,name=co,proto3" json:"co,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ControllerList) Reset()         { *m = ControllerList{} }
func (m *ControllerList) String() string { return proto.CompactTextString(m) }
func (*ControllerList) ProtoMessage()    {}
func (*ControllerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5631c4d876e0f94, []int{2}
}

func (m *ControllerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerList.Unmarshal(m, b)
}
func (m *ControllerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerList.Marshal(b, m, deterministic)
}
func (m *ControllerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerList.Merge(m, src)
}
func (m *ControllerList) XXX_Size() int {
	return xxx_messageInfo_ControllerList.Size(m)
}
func (m *ControllerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerList.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerList proto.InternalMessageInfo

func (m *ControllerList) GetCo() []*ControllerObj {
	if m != nil {
		return m.Co
	}
	return nil
}

func init() {
	proto.RegisterType((*ControllerObj)(nil), "controller.ControllerObj")
	proto.RegisterType((*OvnController)(nil), "controller.OvnController")
	proto.RegisterType((*ControllerList)(nil), "controller.ControllerList")
}

func init() { proto.RegisterFile("proto/controller/controller.proto", fileDescriptor_e5631c4d876e0f94) }

var fileDescriptor_e5631c4d876e0f94 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xd9, 0xe0, 0x4f, 0xc2, 0xf9, 0x8b, 0x21, 0xbd, 0x30, 0x73, 0x57, 0x73, 0x57, 0x18,
	0x93, 0x2d, 0xe2, 0x25, 0x57, 0x84, 0x18, 0x6f, 0x0c, 0x24, 0x25, 0x3e, 0xc0, 0x3a, 0x9a, 0x51,
	0x32, 0xd6, 0xba, 0x1e, 0x88, 0x3e, 0xa6, 0x6f, 0x64, 0xda, 0x4e, 0x18, 0x46, 0x6f, 0xbc, 0xda,
	0x39, 0xbf, 0x9d, 0x7e, 0xdf, 0x77, 0x5a, 0xb8, 0x51, 0xb5, 0x44, 0x99, 0xe6, 0xb2, 0xc2, 0x5a,
	0x96, 0x25, 0xaf, 0x5b, 0x65, 0x62, 0xff, 0x11, 0x38, 0x91, 0xf0, 0xbe, 0x10, 0xb8, 0xd9, 0xb3,
	0x24, 0x97, 0xbb, 0x74, 0xcd, 0xdf, 0x44, 0xf5, 0x9a, 0xee, 0x51, 0x94, 0x3a, 0x75, 0x32, 0x45,
	0x29, 0x59, 0x56, 0x36, 0x1f, 0x77, 0x3c, 0xde, 0xc0, 0x70, 0x7e, 0x14, 0x58, 0xb2, 0x2d, 0x21,
	0xd0, 0x5b, 0x64, 0x3b, 0x1e, 0x78, 0x91, 0x37, 0x1e, 0x50, 0x5b, 0x93, 0x2b, 0xe8, 0xaf, 0x30,
	0xc3, 0xbd, 0x0e, 0xfc, 0xc8, 0x1b, 0xff, 0xa3, 0x4d, 0x47, 0xee, 0xa0, 0x2b, 0x0f, 0x55, 0xd0,
	0x8d, 0xbc, 0xf1, 0xff, 0xc9, 0x75, 0xd2, 0xca, 0xb6, 0x3c, 0x54, 0x27, 0x59, 0x6a, 0xa6, 0xe2,
	0x02, 0x86, 0x67, 0xd4, 0x3a, 0x31, 0xa1, 0x8e, 0x4e, 0x4c, 0x28, 0xc3, 0x56, 0x86, 0xf9, 0x8e,
	0x99, 0xda, 0xb8, 0x2f, 0x98, 0x92, 0x35, 0x5a, 0xa3, 0x01, 0x6d, 0x3a, 0x9b, 0xca, 0xf1, 0x9e,
	0xe3, 0xae, 0x8b, 0xa7, 0x70, 0x79, 0x72, 0x79, 0x16, 0x1a, 0xc9, 0x2d, 0xf8, 0xb9, 0x0c, 0xbc,
	0xa8, 0xfb, 0x3d, 0xe6, 0xd9, 0xea, 0xd4, 0xcf, 0xe5, 0xe4, 0xc3, 0x03, 0x68, 0x65, 0x9c, 0x03,
	0xa1, 0xbc, 0x10, 0x1a, 0x79, 0xdd, 0xa2, 0xbf, 0x6b, 0x84, 0xa3, 0xa4, 0xb9, 0x5e, 0xca, 0xb5,
	0x92, 0x95, 0xe6, 0x71, 0x87, 0xcc, 0x60, 0xf4, 0xa2, 0xd6, 0x19, 0xf2, 0xbf, 0x4b, 0x4c, 0xe1,
	0xe2, 0x89, 0xe3, 0x4c, 0xa9, 0x25, 0xdb, 0xf2, 0x1c, 0xc9, 0xf0, 0x6b, 0xe6, 0x71, 0xa7, 0xf0,
	0x3d, 0x0c, 0x7f, 0x56, 0x33, 0xcb, 0xc7, 0x1d, 0xd6, 0xb7, 0x4f, 0xfd, 0xf0, 0x19, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0xdf, 0xb1, 0xd9, 0x4e, 0x02, 0x00, 0x00,
}
